version: '3'

services: 

  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on: 
       - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: sh -c "npm install && node index.js"
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    build: 
      context: ./database
    container_name: db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 1s
      timeout: 30s
      retries: 300
    

networks: 
  node-network:
    driver: bridge      